### ISSUE TITLE
weberp.xmlrpc_StockAdjustment API throws error 500 when called

### ISSUE THREAD

**Issue by minhnguyen-ew** [timschofield/webERP-svn#24]
I am using Java for communicating with the WebERP XML-RPC API. Call the above API and I receive the error 500 with this log.

`[Thu Mar 29 09:49:17.788294 2018] [:error] [pid 30695] [client 115.79.192.118:41532] PHP Fatal error:  Call to undefined function GetNextTransactionNo() in /var/www/html/jio/api/api_stock.php on line 809`

I am using version 4.14.1 downloaded from SourceForge.

**Comment by andrewcouling** [comment]
I recommend  that you post your query on the WebERP support forum here: http://www.weberp.org/forum/

**Comment by timschofield** [comment]
Try changing the GetNextTransactionNo references to GetNextTransNo in api_stock.php.

@andrewcouling I am told you can sometimes wait days to get your account on the forum.

Tim

**Comment by timschofield** [comment]
I have fixed this issue, you need to download the following files from here:
        api/api_debtortransactions.php
        api/api_stock.php
        api/api_workorders.php
Do not download the whole repo as the xmlrpc library is broken.

Tim

**Comment by minhnguyen-ew** [comment]
Work flawlessly now, thanks.
