### ISSUE TITLE
Wrong $MysqlExt value in installer

### ISSUE THREAD

**Issue by apmuthu** [timschofield/webERP-svn#29]
Lines 939 to 949 in `install/index.php` are:
````
        <?php
        if($MysqlExt){
        ?>
            <input type="hidden" name="MysqlExt" value="1" />
        <?php
        }else{
        ?>
            <input type="hidden" name="MysqliExt" value="1" />
        <?php
        }
        ?>
````
The second `input` element should have value of `0` or be blank.

**Comment by apmuthu** [comment]
Take this fix as part of [this issue](https://github.com/timschofield/webERP-svn/issues/25#issuecomment-377768671)

**Comment by timschofield** [comment]
Thanks, I have applied this fix.

Tim
